In [914]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [915]:
dataset = pd.read_csv("./data/train.csv")
testdataset = pd.read_csv("./data/test.csv")
ids = testdataset.iloc[:, 0].values
# data_missing = dataset.columns[df.isnull().any()].tolist()

# data missing
for col in data_missing:
    print(f"{col} :{dataset[col].isnull().sum()}")

# delete the variables with more than 500 missing values
del dataset["Alley"]
del dataset["FireplaceQu"]
del dataset["PoolQC"]
del dataset["Fence"] 
del dataset["MiscFeature"]
del dataset["Id"]

del testdataset["Alley"]
del testdataset["FireplaceQu"]
del testdataset["PoolQC"]
del testdataset["Fence"] 
del testdataset["MiscFeature"]
del testdataset["Id"]


LotFrontage :259
Alley :1369
MasVnrType :8
MasVnrArea :8
BsmtQual :37
BsmtCond :37
BsmtExposure :38
BsmtFinType1 :37
BsmtFinType2 :38
Electrical :1
FireplaceQu :690
GarageType :81
GarageYrBlt :81
GarageFinish :81
GarageQual :81
GarageCond :81
PoolQC :1453
Fence :1179
MiscFeature :1406


In [916]:
cols_num = [0, 2, 3, 15, 16, 17, 18, 24, 32, 34, 35, 36, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 54, 56, 58, 59, 63, 64, 65, 66, 67, 68, 69, 70, 71]
cols_names = []
for col in dataset.columns:
    cols_names.append(str(col))
for x in range(75):
    if x in cols_num:
        dataset[cols_names[x]] = dataset[cols_names[x]].fillna(dataset[cols_names[x]].mean())

for col in dataset:
    print(f"{col} :{dataset[col].isnull().sum()}")
        

MSSubClass :0
MSZoning :0
LotFrontage :0
LotArea :0
Street :0
LotShape :0
LandContour :0
Utilities :0
LotConfig :0
LandSlope :0
Neighborhood :0
Condition1 :0
Condition2 :0
BldgType :0
HouseStyle :0
OverallQual :0
OverallCond :0
YearBuilt :0
YearRemodAdd :0
RoofStyle :0
RoofMatl :0
Exterior1st :0
Exterior2nd :0
MasVnrType :8
MasVnrArea :0
ExterQual :0
ExterCond :0
Foundation :0
BsmtQual :37
BsmtCond :37
BsmtExposure :38
BsmtFinType1 :37
BsmtFinSF1 :0
BsmtFinType2 :38
BsmtFinSF2 :0
BsmtUnfSF :0
TotalBsmtSF :0
Heating :0
HeatingQC :0
CentralAir :0
Electrical :1
1stFlrSF :0
2ndFlrSF :0
LowQualFinSF :0
GrLivArea :0
BsmtFullBath :0
BsmtHalfBath :0
FullBath :0
HalfBath :0
BedroomAbvGr :0
KitchenAbvGr :0
KitchenQual :0
TotRmsAbvGrd :0
Functional :0
Fireplaces :0
GarageType :81
GarageYrBlt :0
GarageFinish :81
GarageCars :0
GarageArea :0
GarageQual :81
GarageCond :81
PavedDrive :0
WoodDeckSF :0
OpenPorchSF :0
EnclosedPorch :0
3SsnPorch :0
ScreenPorch :0
PoolArea :0
MiscVal :0
MoSold :0
YrSold :0

In [917]:

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

types = set()
type_num = ["<class 'float'>", "<class 'int'>"]
cols_num = []
cols_str = []
for col in range(74):
    if str(type(X[0, col])) in type_num:
        cols_num.append(col)
    elif str(type(X[0, col])) == "<class 'str'>":
        cols_str.append(col)
        
    types.add(str(type(X[0, col])))
print(types)
print(cols_num)
print(cols_str)




{"<class 'str'>", "<class 'float'>", "<class 'int'>"}
[0, 2, 3, 15, 16, 17, 18, 24, 32, 34, 35, 36, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 54, 56, 58, 59, 63, 64, 65, 66, 67, 68, 69, 70, 71]
[1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 33, 37, 38, 39, 40, 51, 53, 55, 57, 60, 61, 62, 72, 73]


In [918]:

X_test = testdataset.iloc[:, :].values
print(X_test.shape)

types2 = set()
type_num2 = ["<class 'float'>", "<class 'int'>"]
cols_num2 = []
cols_str2 = []
for col in range(74):
    if str(type(X_test[0, col])) in type_num2:
        cols_num2.append(col)
    elif str(type(X_test[0, col])) == "<class 'str'>":
        cols_str2.append(col)
        
    types2.add(str(type(X_test[0, col])))
print(types2)
print(cols_num2)
print(cols_str2)



(1459, 74)
{"<class 'str'>", "<class 'float'>", "<class 'int'>"}
[0, 2, 3, 15, 16, 17, 18, 24, 32, 34, 35, 36, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 54, 56, 58, 59, 63, 64, 65, 66, 67, 68, 69, 70, 71]
[1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 33, 37, 38, 39, 40, 51, 53, 55, 57, 60, 61, 62, 72, 73]


In [919]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy= "most_frequent")
imputer2 = SimpleImputer(missing_values=np.nan, strategy= "mean")
imputer.fit(X)
X = imputer.transform(X)




In [920]:
print(X.shape)
from sklearn.impute import SimpleImputer
imputer2 = SimpleImputer(missing_values=np.nan, strategy= "most_frequent")
imputer2.fit(X_test)
X_test = imputer.transform(X_test)

print(X_test.shape)


(1460, 74)
(1459, 74)


In [921]:
print(X.shape)
from sklearn.preprocessing import StandardScaler
ct = ColumnTransformer(transformers=[('somename', StandardScaler(with_mean=False), cols_num )], remainder='passthrough')
X = ct.fit_transform(X)
print(X.shape)
sc = StandardScaler()
y = y.reshape(-1,1)
y = sc.fit_transform(y)

(1460, 74)
(1460, 74)


In [922]:

ct2 = ColumnTransformer(transformers=[('somename2', StandardScaler(with_mean=False), cols_num2 )], remainder='passthrough')
X_test = ct2.fit_transform(X_test)
print(X_test.shape)

(1459, 74)


In [923]:


types = set()
type_num = ["<class 'float'>", "<class 'int'>"]
cols_num = []
cols_str = []
for col in range(74):
    if str(type(X[0, col])) in type_num:
        cols_num.append(col)
    elif str(type(X[0, col])) == "<class 'str'>":
        cols_str.append(col)
        
    types.add(str(type(X[0, col])))
print(types)
print(cols_num)
print(cols_str)



{"<class 'str'>", "<class 'float'>"}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]


In [924]:
X2 = np.concatenate((X, X_test), axis=0)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), cols_str )], remainder='passthrough')
X2 = ct.fit_transform(X2)
X3 = X2[0:1460,:]
X_test3 = X2[1460:,:]
print(X_test3.shape)
print(X.shape)
print(X3.shape)

(1459, 270)
(1460, 74)
(1460, 270)


In [925]:
from sklearn.ensemble import RandomForestRegressor
classifier = RandomForestRegressor(n_estimators=1000)
classifier.fit(X3, y.ravel())

results = classifier.predict(X_test3)
results = sc.inverse_transform(results.reshape(-1,1))
print(results)

[[130192.596]
 [161850.368]
 [185117.948]
 ...
 [145078.633]
 [114994.47 ]
 [236481.732]]


In [926]:
results.shape
ids = ids.astype(int)
results2 = np.column_stack((ids, results))
results2[:,0] = np.floor(results2[:,0])
print(results2[:,0])
print(results2.shape)



[1461. 1462. 1463. ... 2917. 2918. 2919.]
(1459, 2)


In [927]:

results3 = results2.astype(int)
print(results3.shape)
print(results2)

(1459, 2)
[[  1461.    130192.596]
 [  1462.    161850.368]
 [  1463.    185117.948]
 ...
 [  2917.    145078.633]
 [  2918.    114994.47 ]
 [  2919.    236481.732]]


In [928]:
names = ["Id","SalePrice"]
df = pd.DataFrame(results3, columns=names)
df.to_csv('results4.csv', index=False, header=True, sep=',')

In [929]:
df = pd.DataFrame(results2, columns=names)
df["Id"] = pd.to_numeric(df["Id"], downcast="integer")
df.to_csv('results5.csv', index=False, header=True, sep=',')